# Generated by Django 6.1.1 on 2026-10-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_refund_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunding', 'Refunding'), ('refunded', 'Refunded'), ('refund_failed', 'Refund failed')], default='pending', max_length=20),
        ),
    ]
