# Generated by Django 6.1.1 on 2026-10-08 16:48

from django.db import migrations, models

NO_OVERLAP = 'showtime_no_overlap_in_hall'


def add_no_overlap(apps, schema_editor):
    # Exclusion constraints exist only in PostgreSQL. On SQLite (tests, local dev)
    # the serializer's overlap check is the only guard.
    if schema_editor.connection.vendor != 'postgresql':
        return
    table = schema_editor.quote_name(apps.get_model('showtimes', 'Showtime')._meta.db_table)
    # btree_gist lets a GiST index compare hall_id with "=" next to the range's "&&".
    schema_editor.execute('CREATE EXTENSION IF NOT EXISTS btree_gist')
    # '[)' leaves out the end instant, so one show may start the moment the last one ends.
    schema_editor.execute(
        f"ALTER TABLE {table} ADD CONSTRAINT {NO_OVERLAP} "
        f"EXCLUDE USING gist (hall_id WITH =, tstzrange(start_time, end_time, '[)') WITH &&)"
    )


def drop_no_overlap(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return
    table = schema_editor.quote_name(apps.get_model('showtimes', 'Showtime')._meta.db_table)
    schema_editor.execute(f'ALTER TABLE {table} DROP CONSTRAINT IF EXISTS {NO_OVERLAP}')


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_hall_total_rows_hall_total_seats_per_row'),
        ('movies', '0003_movie_backdrop'),
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='showtime',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='showtime_ends_after_start'),
        ),
        migrations.RunPython(add_no_overlap, drop_no_overlap),
    ]
