# Generated by Django 6.1.1 on 2026-09-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='total_rows',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='total_seats_per_row',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
