# Generated by Django 6.1.1 on 2026-09-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('trailer_url', models.URLField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('age_rating', models.CharField(choices=[('G', 'General'), ('PG', 'Parental Guidance'), ('PG-13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults Only')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
