# Generated by Django 6.1.1 on 2026-09-10 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='backdrop',
            field=models.ImageField(blank=True, null=True, upload_to='movie_backdrops/'),
        ),
    ]
